services:
  # 💡 ИСПРАВЛЕНИЕ: Замена CockroachDB на PostgreSQL
  postgres: # <-- Смена имени сервиса
    image: postgres:15-alpine
    # EN: Database settings defined in .env file
    # RU: Настройки базы данных, определенные в .env
    environment:
      POSTGRES_USER: hom_user
      POSTGRES_PASSWORD: hom_pass
      POSTGRES_DB: hom_db
    ports: ["5432:5432"] # <-- Стандартный порт PG
    volumes: [ "pg-data:/var/lib/postgresql/data" ] # <-- Новый том данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hom_user -d hom_db"] # <-- Проверка статуса PG
      interval: 5s
      timeout: 3s
      retries: 5

  redis: 
    image: redis:7.2-alpine
    command: redis-server --appendonly yes
    ports: ["6379:6379"]
    volumes: ["redis-data:/data"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      postgres: # <-- ИЗМЕНЕНИЕ ЗАВИСИМОСТИ
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - APP_ENV=dev
      # 💡 ИЗМЕНЕНИЕ: DB_URL теперь ссылается на сервис 'postgres'
      - DB_URL=postgresql+asyncpg://hom_user:hom_pass@postgres:5432/hom_db 
      - JWT_SECRET=dev-secret-change-me
      - JWT_EXPIRE_MIN=60
      - CORS_ORIGINS=http://localhost:5173
      - REDIS_URL=redis://redis:6379
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    depends_on: [ backend ]
    environment:
      - VITE_API_URL=http://localhost:8000
    ports: ["5173:5173"]

volumes:
  pg-data: # <-- НОВЫЙ ТОМ
  redis-data: