services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.2.2
    command: start-single-node --insecure --http-addr=0.0.0.0:8080 --sql-addr=0.0.0.0:26257
    ports: ["26257:26257","8080:8080"]
    volumes: [ "crdb-data:/cockroach/cockroach-data" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build: ./backend
    depends_on:
      cockroachdb:
        condition: service_healthy
    environment:
      - APP_ENV=dev
      - DB_URL=postgresql+asyncpg://root@cockroachdb:26257/hom?sslmode=disable
      - JWT_SECRET=dev-secret-change-me
      - JWT_EXPIRE_MIN=60
      - CORS_ORIGINS=http://localhost:5173
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    depends_on: [ backend ]
    environment:
      - VITE_API_URL=http://localhost:8000
    ports: ["5173:5173"]

volumes:
  crdb-data:
