name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    
    # 💾 Настройка зависимых сервисов (Postgres и Redis) для интеграционного тестирования
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: hom_user
          POSTGRES_PASSWORD: hom_pass
          POSTGRES_DB: hom_db
        # Настройка healthcheck и имени сервиса (для разрешения имен хостов в тестах)
        options: >-
          --health-cmd "pg_isready -U hom_user -d hom_db"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
          --name hom_postgres
        ports:
          - 5432:5432
      redis:
        image: redis:7.2-alpine
        command: redis-server --appendonly yes
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 3s
          --health-timeout 3s
          --health-retries 5
          --name hom_redis
        ports:
          - 6379:6379

    defaults:
      run:
        working-directory: backend
        
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps & Test dependencies
        run: |
          python -m pip install --upgrade pip
          # Устанавливаем все зависимости, включая инструменты качества и тестирования
          pip install -r requirements.txt
          pip install ruff black mypy pytest pytest-asyncio httpx

      - name: 🔬 Ruff (Check Formatting & Linting)
        # ✅ Только проверка, авто-фикс выполняется локально (через pre-commit)
        run: ruff check .

      - name: 🎨 Black (Check Formatting)
        # ✅ Только проверка
        run: black . --check

      - name: 📝 Mypy (Static Type Check)
        run: |
          mypy --ignore-missing-imports .
      
      - name: 🚀 Run Tests (Unit & Integration)
        # GitHub Actions автоматически ждет, пока сервисы станут здоровыми (health check)
        run: |
          pytest
        env:
          # Переопределение переменных окружения для тестов, чтобы они использовали имена сервисов (postgres, redis), 
          # которые доступны в сети GitHub Actions
          DB_URL: postgresql+asyncpg://hom_user:hom_pass@postgres:5432/hom_db
          REDIS_URL: redis://redis:6379
          JWT_SECRET: test-secret-for-ci # Используем тестовый секрет


  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build (sanity)
        # Проверяет, что сборка проходит без ошибок, используя переменные из docker-compose
        env:
          VITE_API_URL: http://localhost:8000
        run: npm run build