name: CI/CD

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black mypy

      # --- Ruff ---
      - name: Ruff Lint
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Running Ruff in fix mode (main branch)..."
            ruff check . --fix || true
          else
            echo "Running Ruff in check mode (feature/pr)..."
            ruff check .
          fi

      # --- Black ---
      - name: Black Formatting
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Running Black auto-fix (main branch)..."
            black . || true
          else
            echo "Running Black check (feature/pr)..."
            black --check .
          fi

      # --- Mypy ---
      - name: Mypy (Type Check)
        run: |
          mypy --ignore-missing-imports .

  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 🧹 Fix Rollup optional dependency bug
      - name: Clean and install deps (fix rollup bug)
        run: |
          echo "Cleaning node_modules and npm cache..."
          rm -rf node_modules package-lock.json
          npm cache clean --force
          echo "Installing dependencies..."
          npm install --force

      # 🧱 Build step
      - name: Build (sanity check)
        env:
          VITE_API_URL: http://localhost:8000
        run: npm run build
