# .github/workflows/ci.yml (фрагмент в job: backend-ci)

      - name: Black (check only)
        # ❌ ИЗМЕНЕНО: Не фиксируем, а проверяем
        run: |
          black . --check 

      - name: Mypy (loose)
        run: |
          mypy --ignore-missing-imports .
          
      # ✅ ДОБАВЛЕНО: Запуск тестов
      - name: Run Tests
        # Используем docker-compose для поднятия Postgres/Redis для тестов
        run: |
          cd ..
          docker compose up -d postgres redis
          # Ждем, пока сервисы станут здоровыми (для тестов можно использовать wait-for-it.sh или команду из entrypoint.sh)
          # Здесь упрощенный вариант:
          until nc -z localhost 5432; do echo "⏳ Waiting for Postgres..."; sleep 1; done
          until nc -z localhost 6379; do echo "⏳ Waiting for Redis..."; sleep 1; done
          cd backend
          # Запускаем pytest, используя локальные зависимости
          pytest --asyncio-mode=strict
        env:
          # Переопределяем URL для тестов, чтобы они указывали на localhost, а не на имя контейнера
          DB_URL: postgresql+asyncpg://hom_user:hom_pass@localhost:5432/hom_db
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-secret # Используем тестовый секрет
          # ... другие необходимые переменные
          
      # ✅ ДОБАВЛЕНО: Закрытие контейнеров
      - name: Cleanup Test Environment
        if: always()
        run: |
          cd ..
          docker compose down