name: ci

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]
  pull_request: {}


jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: python -m compileall app

  # 🐳 Docker build job
  docker-build:
    runs-on: ubuntu-latest
    needs: [backend]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # ✅ Преобразуем имя репозитория в строчные буквы
      - name: Set lowercase repository name
        id: repo_name
        shell: bash
        run: |
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$REPO_LOWER" >> "$GITHUB_OUTPUT"

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images to GHCR
        env:
          REPO_LOWER: ${{ steps.repo_name.outputs.REPO_LOWER }}
        run: |
          echo "Building and pushing images for: ghcr.io/$REPO_LOWER"
          docker build -t ghcr.io/$REPO_LOWER/hom-backend:main ./backend
          docker build -t ghcr.io/$REPO_LOWER/hom-frontend:main ./frontend

          docker push ghcr.io/$REPO_LOWER/hom-backend:main
          docker push ghcr.io/$REPO_LOWER/hom-frontend:main


  # 🚀 Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      # 💡 НОВЫЙ ШАГ: Сначала определяем все переменные, которые нужны в скрипте SSH
      - name: Define deployment environment variables
        id: deploy_env
        shell: bash
        run: |
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$REPO_LOWER" >> "$GITHUB_OUTPUT"
          echo "DB_URL_STAGE=${{ secrets.DB_URL_STAGE }}" >> "$GITHUB_OUTPUT"
          echo "JWT_SECRET_STAGE=${{ secrets.JWT_SECRET_STAGE }}" >> "$GITHUB_OUTPUT"
          echo "CORS_ORIGINS_STAGE=${{ secrets.CORS_ORIGINS_STAGE }}" >> "$GITHUB_OUTPUT"
          echo "REMOTE_HOST=${{ secrets.REMOTE_HOST }}" >> "$GITHUB_OUTPUT"

      - name: Deploy to DigitalOcean Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.deploy_env.outputs.REMOTE_HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 💡 ИСПРАВЛЕНИЕ: Явно передаем переменные в удаленный скрипт
          envs: REPO_LOWER,DB_URL_STAGE,JWT_SECRET_STAGE,CORS_ORIGINS_STAGE,REMOTE_HOST
          script: |
            # set -euo pipefail # ⚠️ Можно оставить, если уверены, что все переменные переданы
            set -e # Оставим только set -e (выйти при ошибке), так как -u вызвал проблему

            DEPLOY_DIR="/var/www/hom_mvp/stage"
            # 💡 Переменная REPO_LOWER теперь доступна
            IMAGE_REPO="ghcr.io/${REPO_LOWER}"

            echo ">>> Creating stage.env on remote server..."
            mkdir -p "${DEPLOY_DIR}"
            cd "${DEPLOY_DIR}"

            # 💡 Переменные доступны напрямую в HEREDOC
            cat <<EOF > stage.env
            DB_URL=${DB_URL_STAGE}
            JWT_SECRET=${JWT_SECRET_STAGE}
            CORS_ORIGINS=${CORS_ORIGINS_STAGE}
            APP_ENV=staging
            JWT_EXPIRE_MIN=60
            VITE_API_URL=http://${REMOTE_HOST}:8000
            BACKEND_IMAGE=${IMAGE_REPO}/hom-backend:main
            FRONTEND_IMAGE=${IMAGE_REPO}/hom-frontend:main
            EOF

            echo ">>> Deploying docker-compose.stage.yml..."
            docker compose -f docker-compose.stage.yml pull
            docker compose -f docker-compose.stage.yml up -d --force-recreate

            echo "✅ Deployment to Droplet finished successfully."