name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      # --- Клонирование репозитория ---
      - uses: actions/checkout@v4

      # --- Настройка SSH-доступа ---
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts

      # --- Проверка секретов ---
      - name: Validate required GitHub Secrets
        env:
          DB_URL_STAGE: ${{ secrets.DB_URL_STAGE }}
          JWT_SECRET_STAGE: ${{ secrets.JWT_SECRET_STAGE }}
          CORS_ORIGINS_STAGE: ${{ secrets.CORS_ORIGINS_STAGE }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          echo "Validating secrets..."
          REQUIRED_VARS=("DB_URL_STAGE" "JWT_SECRET_STAGE" "CORS_ORIGINS_STAGE" "REMOTE_HOST")
          for VAR in "${REQUIRED_VARS[@]}"; do
            VALUE="${!VAR}"
            if [ -z "$VALUE" ]; then
              echo "❌ Missing secret: $VAR"
              exit 1
            fi
            echo "✅ $VAR present"
          done
          echo "✅ All required secrets are present."

      # --- Проверка .env.stage ---
      - name: Validate .env.stage content
        env:
          DB_URL_STAGE: ${{ secrets.DB_URL_STAGE }}
          JWT_SECRET_STAGE: ${{ secrets.JWT_SECRET_STAGE }}
          CORS_ORIGINS_STAGE: ${{ secrets.CORS_ORIGINS_STAGE }}
        run: |
          echo "Validating .env.stage..."
          echo "CORS_ORIGINS=$CORS_ORIGINS_STAGE"
          
          if [ -z "$DB_URL_STAGE" ]; then
            echo "❌ DB_URL_STAGE is empty!"
            exit 1
          fi
          if [ -z "$JWT_SECRET_STAGE" ]; then
            echo "❌ JWT_SECRET_STAGE is empty!"
            exit 1
          fi
          if [ -z "$CORS_ORIGINS_STAGE" ]; then
            echo "❌ CORS_ORIGINS_STAGE is empty!"
            exit 1
          fi
          if ! echo "$CORS_ORIGINS_STAGE" | grep -E '^(\[|http)'; then
            echo "❌ Invalid CORS_ORIGINS_STAGE format. Should be JSON or URL."
            exit 1
          fi
          echo "✅ .env.stage variables look good."

      # --- Загрузка проекта на сервер ---
      - name: Push repo to droplet
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          echo "📦 Uploading project to server..."
          rsync -az --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            ./ "deployer@$REMOTE_HOST:/home/deployer/dev/hom_mvp"

      # --- Создание .env.stage на сервере ---
      - name: Write .env.stage on server
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          DB_URL_STAGE: ${{ secrets.DB_URL_STAGE }}
          JWT_SECRET_STAGE: ${{ secrets.JWT_SECRET_STAGE }}
          CORS_ORIGINS_STAGE: ${{ secrets.CORS_ORIGINS_STAGE }}
        run: |
          echo "📝 Writing .env.stage file on server..."
          ssh "deployer@${REMOTE_HOST}" bash -lc "'
            set -e
            cd /home/deployer/dev/hom_mvp
            cat <<EOF > .env.stage
            APP_ENV=stage
            DB_URL=${DB_URL_STAGE}
            JWT_SECRET=${JWT_SECRET_STAGE}
            JWT_EXPIRE_MIN=60
            CORS_ORIGINS=${CORS_ORIGINS_STAGE}
            REDIS_URL=redis://redis:6379
            EOF
            echo \"✅ .env.stage created successfully\"
          '"

      # --- Пересборка и деплой ---
      - name: Compose up (stage)
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          echo "🚀 Deploying to stage..."
          ssh "deployer@${REMOTE_HOST}" bash -lc '
            set -e
            cd /home/deployer/dev/hom_mvp

            echo "🧱 Pulling latest images..."
            docker compose -f docker-compose.stage.yml pull || true

            echo "🔁 Rebuilding backend if necessary..."
            docker compose -f docker-compose.stage.yml build backend

            echo "🚀 Starting containers..."
            docker compose -f docker-compose.stage.yml up -d --remove-orphans

            echo "🔍 Checking container status..."
            docker compose -f docker-compose.stage.yml ps
          '
